### ISSUE TITLE
Support for latest OS's?

### ISSUE THREAD

**Issue by pelicanmedia** [pimoroni/hyperpixel2r#11]
Hi,

Is there going to be any updates for the latest Raspberry Pi OS's, there was meant to be work going on for 'Bullseye' as still mentioned on the [Hyperpixel 2.1 Round](https://shop.pimoroni.com/products/hyperpixel-round?variant=39381081882707#:~:text=We%27re%20working%20on%20full%20support%20for%20Bullseye) page.

Is there going to be support for the newest 'Bookworm' also?

**Comment by Gadgetoid** [comment]
Round is, as far as I know, as supported as it's going to get. There's a dtoverlay that enables the display, but the pins for touch are impossibly conflicted such that Bullseye and Bookworm simply wont let us use them for two things at the same time (sending the display init routine, and then switching to touch). This is a consequence of Pi moving away from their custom DPI display config in config.txt, and memory-mapped GPIO access, toward a stricter, Linux way of doing things.

Discussion around migrating HyperPixel to the new ways of doing things happened here, and there has - afaik - been no breakthrough since: https://forums.raspberrypi.com/viewtopic.php?t=324640

Short of some IO multiplexing miracle happening within the Linux kernel itself, this is irreconcilable. There might be some incredibly contrived way to hack around it, but since Bookworm has broken basically _everything_ else I don't have the time to investigate right now.

**Comment by pelicanmedia** [comment]
Thanks for the quick reply.
That is a shame, I had some projects lined up to use those screens and prefer to use up-to-date OSs where possible.

I haven't quite gotten around to looking at Bookworm in depth as yet, but from what little I have read so far, it has broken quite a lot!

Thanks again for taking the time to reply.

**Comment by Gadgetoid** [comment]
I did miss out mentioning that I want to investigate using an RP2040 to init the display or bridge the touchscreen somehow. Mostly because making hardware modifications to the screens is a bit out of the comfort zone of some folks. Some kind of HyperPixel mod chip project is on my long, long todo list though!

**Comment by pelicanmedia** [comment]
I'm not afraid of using a soldering iron and a hammer!
