### ISSUE TITLE
Typo in C src file for CLK and MOSI

### ISSUE THREAD

**Issue by VladutLP** [pimoroni/hyperpixel2r#4]
I wanted to push a PR for:

https://github.com/pimoroni/hyperpixel2r/blob/9a7496e73de9373476e02f28918d66d0ec1cab94/src/hyperpixel2r-init.c#L7
https://github.com/pimoroni/hyperpixel2r/blob/9a7496e73de9373476e02f28918d66d0ec1cab94/src/hyperpixel2r-init.c#L8

As they should be
```
#define CLK 11
#define MOSI 10
```
(Inspired from the python init script)

But simply changing them will result in a Seg Fault because usually the i2c lines are initialized/used.

After a `modeprobe -r i2c_dev` or anything related to i2c the init runs almost smooth. 
The only problem is that the characters on the display are at 30% brightness compared to the python script. (Actual pixels not the backlight)

I'll check the commands from the python file are the same in the c one but I have no idea how we should handle the i2c part as that would imply to modeprobe back the i2c and the touch driver which sounds hacky. 

I thought of following PINN's [implementation](https://github.com/procount/pinn/blob/master/cypress2/touchscreen/pimhyp3.c) for hyperpixel 3 and 4 and extend the FT5x06 driver with the init of the display but atm I lack that kind of power and knowledge.
(Maybe @procount could lend a hand?)

**Comment by procount** [comment]
It can't need that much power and knowledge as my drivers for hyperpixel 3 & 4 were my first foray into Linux device drivers :wink:
With the current trend for upstreaming, the preferred route these days is probably to use the panel drivers as mentioned here -> https://forums.raspberrypi.com/viewtopic.php?t=324640/. Later posts indicate the 2r might need more development effort. I'm not really up to speed on the panel drivers.

**Comment by Gadgetoid** [comment]
I'm somewhat taken aback that I hadn't noticed the pin change before. Or perhaps achknowledged and forgotten.

I don't know how it's cramming SPI and i2c down the same pins like this without upsetting the touch driver. Sufice to say - as you've noted with the gpiod C code - Linux does not much like this.

I'm not sure there's a workaround from userspace libgpiod. As @procount rightfully suggests, all of these userspace hacks are set to be obsolete anyway- providing it's possible for device-tree/kernel drivers to work around some of our balmy design choices.

Incidentally this issue led me to ask about this on the ongoing HyperPixel upstream support PR and solve some mysteries with HyperPixel 2 Round... we're making progress at least.

For future products I'm fighting the battle to avoid pin conflicts altogether- though it's unclear how best to achieve that.

**Comment by VladutLP** [comment]
> I'm somewhat taken aback that I hadn't noticed the pin change before.

I've seen worse in web dev :D 

> I don't know how it's cramming SPI and i2c down the same pins like this without upsetting the touch driver. 

Maybe the fantom touches that other people are reporting are related to this?

> With the current trend for upstreaming, the preferred route these days is probably to use the panel drivers as mentioned here -> https://forums.raspberrypi.com/viewtopic.php?t=324640/.

It was so wholesome and amusing reading this, especially that you guys lived/worked in the same city.
Also looking over the code and the dts for hyp4 gave me an idea. 

Can a device tree device be set up in a way to be a proxy for pins?
Ex:
```
   @virtual-device
              -pin 1
              -pin 2
              -virtual pin 3

   @display-ic
              -virtual device pin 1
              -virtual device pin 2
              -pin 3
              -......

   @touch-ic
            -virtual device pin 1
            -virtual device pin 2
```
And we could set the virtual device pin 3 to something so it would know to switch between SPI and i2c

**Comment by Gadgetoid** [comment]
I think the "proxy" you talk about is what GPIO finite state machine might be *possibly* appropriate for, but I don't think it has much history of being used with kernel-level drivers such as i2c/SPI - https://forums.raspberrypi.com/viewtopic.php?p=1821505#p1821505

There's a lot more discussion and progress on mainlining HyperPixel board support here - https://github.com/raspberrypi/linux/pull/4812 which also highlights some of the wider issues getting these kinds of displays to work. Oh for HDMI, HDMI everywhere :laughing: 

I have - uh - summarily deleted the C++ init code from this repository because it's multiple levels of wrong. Hopefully it will be usefully replaced by driver code otherwise it might take some gymnastics to bitbang those pins and *then* load a dtoverlay on the fly to handle touch.

You can omit `dtoverlay=hyperpixel2r` from `/boot/config.txt` and just use the `dtoverlay` command at runtime to load it. This works pretty reliably, and is how I actually work on dtoverlay tweaks without having to reboot constantly. Bitbanging the SPI init from C++, releasing the pins, and *then* loading the dtoverlay for touch should work.
